image: gcc:latest

variables:
  BUILD_DIR: build
  NEXUS_URL: ${NEXUS_URL}
  NEXUS_USERNAME: ${NEXUS_USERNAME}
  NEXUS_PASSWORD: ${NEXUS_PASSWORD}
  NEXUS_REPOSITORY: ${NEXUS_REPOSITORY}

stages:
  - build
  - test
  - package
  - deploy

before_script:
  - apt-get update -qq
  - apt-get install -y -qq cmake rpm curl

build:
  stage: build
  script:
    - mkdir -p $BUILD_DIR
    - cd $BUILD_DIR
    - cmake ..
    - make
  artifacts:
    paths:
      - $BUILD_DIR/calculator
      - $BUILD_DIR/calculator_test

test:
  stage: test
  script:
    - cd $BUILD_DIR
    - ./calculator_test
  dependencies:
    - build

package:
  stage: package
  script:
    - cd $BUILD_DIR
    - cmake ..
    - cat CPackConfig.cmake
    - cpack --config CPackConfig.cmake
  artifacts:
    paths:
      - $BUILD_DIR/*.rpm
  dependencies:
    - build

deploy:
  stage: deploy
  script:
    - |
      for rpm_file in $BUILD_DIR/*.rpm; do
        echo "Uploading $rpm_file to Nexus..."
        curl -v -u "$NEXUS_USERNAME:$NEXUS_PASSWORD" \
          --upload-file "$rpm_file" \
          "$NEXUS_URL/repository/$NEXUS_REPOSITORY/$(basename $rpm_file)"
      done
  dependencies:
    - package
  only:
    - main 